### PR TITLE
More compact cookieLogger function

### PR DESCRIPTION
**Pull request by Dr-Insanity**
+ Added brave browser

### CODE REVIEW

**Comment by Dr-Insanity** [comment]
Your welcome! :D

**Comment by Mehrabopera** [comment]
HELP ):

**Comment by Mehrabopera** [comment]
how do I use this nigga

**Review by Mani175 — CHANGES_REQUESTED** [review]
yo this is actually kinda fire

if you could make it so it gets the avatar picture for the webhook pfp then
i will actually put you in the credits fr

**Comment by Dr-Insanity** [comment]
Okay. On it.

**Comment by Dr-Insanity** [comment]
Because an embed's field's value has now a lower character limit, we'll have to move the token to a file or some other type of field which allows more characters. Is this okay?

I included a screenshot. See for yourself.
image

**Comment by Teslaguy2** [comment]
I installed roblox py but the pirate grabber keeps saying Libraries not installed press enter to exit...

what do i do?

**Comment by Amiine7** [comment]
man how tf i use it. it says always "libraries not installed" please do a tuto or tell us on discord (give server link)

**Comment by Dr-Insanity** [comment]
@Mani175 Fun fact about turning your python scripts into executables with pyinstaller: People won't need to download python and install any dependencies. Try to make releases in your repositories. Also, I need your approval if you're okay with the result posted in above screenshot.

**Comment by Dr-Insanity** [comment]
> man how tf i use it. it says always "libraries not installed" please do a tuto or tell us on discord (give server link)

You'll need to install more than that.

Assuming pip is on your PATH
```bash
pip install pip requests discordwebhook.py browser-cookie3 --upgrade --user
```

That should do it.

**Comment by Kinguuu34** [comment]
> > man how tf i use it. it says always "libraries not installed" please do a tuto or tell us on discord (give server link)
> 
> @Amiine7, You'll need to install more than that.
> 
> Assuming pip is on your PATH
> 
> ```shell
> pip install pip requests discordwebhook.py browser-cookie3 --upgrade --user
> ```
> 
> That should do it.

where do you even insert this

**Comment by Dr-Insanity** [comment]
In your Terminal

**Comment by Dr-Insanity** [comment]
Look, no one is supposed to ask questions here. It's off-topic. This is a pull request, not a support ticket.

**Comment by Incognito12143** [comment]
> Look, no one is supposed to ask questions here. It's off-topic. This is a pull request, not a support ticket.

If this is where you pull someone can you do someone that got a titanic or is very rich in pet simulator? trynna sell that shi fr

**Comment by Mani175** [comment]
> Because an embed's field's value has now a lower character limit, we'll have to move the token to a file or some other type of field which allows more characters. Is this okay?
> 
> I included a screenshot. See for yourself. image

tbh bro do whatever you want with the script, if you could actually remaster this you're gonna get a good reward my man :)

**Pull request closed without merging**
